### ISSUE TITLE
Published extension

### ISSUE THREAD

**Issue by agentcooper** [jikamens/chrome-lj-tos-hider#2]
Hey.

Unaware of your extension, I made the same one: https://chrome.google.com/webstore/detail/livejournal-tos-popup-rem/onhfpcnpbngcpihngedgmfpjejnhnlil. Just FYI.

**Comment by jikamens** [comment]
The more the merrier. I would point out, however, that it appears that your extension hides the TOS pop-up on every LiveJournal page, whereas mine only hides the pop-up on the accountstatus page. As much as I may object to the new LiveJournal Terms of Service, it's their right to impose those terms, and I would not presume to release an extension intended to assist people in evading them.

However, I do not think it is appropriate for people to have to agree to the new TOS in order to delete their accounts, and indeed, I think the fact that they need to do so is simply an omission on the part of the LiveJournal maintainers, one which I'm comfortable releasing an extension to address.
